[tool.poetry]
name = "photo-derush"
version = "0.1.0"
description = "A tool to dereush photography session with IA"
authors = ["yrolland <rolland_yann@orange.fr>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pillow = "^11.3.0"
pytest = "^8.4.1"
imagehash = "^4.3.2"
faiss-cpu = "^1.11.0"
opencv-python = "^4.12.0.88"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
